<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <xacro:include filename="inertial_macros.xacro"/>

    <xacro:property name="chassis_length" value="0.65"/>
    <xacro:property name="chassis_width" value="0.45"/>
    <xacro:property name="chassis_height" value="0.25"/>
    <xacro:property name="chassis_mass" value="1.0"/>
    <xacro:property name="wheel_radius" value="0.06"/>
    <xacro:property name="wheel_thickness" value="0.025"/>
    <xacro:property name="wheel_mass" value="0.05"/>
    <xacro:property name="wheel_offset_x" value="${chassis_length/2}"/>
    <xacro:property name="wheel_offset_y" value="${chassis_width/2 - wheel_thickness }"/>
    <xacro:property name="wheel_offset_z" value="${wheel_radius - 2*caster_wheel_radius }"/>
    <xacro:property name="caster_wheel_radius" value="0.0135"/>
    <xacro:property name="caster_wheel_mass" value="0.01"/>
    <xacro:property name="caster_wheel_offset_x1" value="${chassis_length - 0.1}"/>
    <xacro:property name="caster_wheel_offset_x2" value="0.1"/>
    <xacro:property name="caster_wheel_offset_y" value="0.125"/>
    <xacro:property name="caster_wheel_offset_z" value="${-caster_wheel_radius}"/>

    <!-- MATERIAL COLOR-->

    <material name= "blue">
        <color rgba= "0 0 1 1" />
    </material>
    <material name= "green">
        <color rgba= "0 1 0 1" />
    </material>
    <material name= "red">
        <color rgba= "1 0 0 1" />
    </material>
    <material name= "black">
        <color rgba= "0 0 0 1" />
    </material>
    <material name= "white">
        <color rgba= "1 1 1 1" />
    </material>
    <material name= "yellow">
        <color rgba= "1 0.9 0.2 1" />
    </material>

    <!-- BASE LINK -->

    <link name="base_link">

    </link>

    <!-- BASE_FOOTPRINT LINK -->

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="base_footprint">
    </link>


    <!-- CHASSIS LINK -->

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="${-wheel_offset_x} 0 ${-wheel_offset_z}"/>
    </joint>

    <link name="chassis">
        <visual>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.5" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="chassis">
        <material>Gazebo/Blue</material>
    </gazebo>

    <!-- LEFT WHEEL LINK -->

    <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel"/>
        <origin xyz="0 ${wheel_offset_y} 0" rpy="-${pi/2} 0 0" />
        <axis xyz="0 0 1"/>
    </joint>

    <link name="left_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="left_wheel">
        <material>Gazebo/Blace</material>
    </gazebo>




    <!-- RIGHT WHEEL LINK -->

    <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel"/>
        <origin xyz="0 ${-wheel_offset_y} 0" rpy="${pi/2} 0 0" />
        <axis xyz="0 0 -1"/>
    </joint>

    <link name="right_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="right_wheel">
        <material>Gazebo/Black</material>
    </gazebo>


    <!-- CASTER WHEEL LINK -->

    <joint name="caster_wheel_joint1" type="fixed">
        <parent link="chassis"/>
        <child link="caster_wheel1"/>
        <origin xyz="${caster_wheel_offset_x1} ${caster_wheel_offset_y} ${caster_wheel_offset_z}"/>
    </joint>

    <joint name="caster_wheel_joint2" type="fixed">
        <parent link="chassis"/>
        <child link="caster_wheel2"/>
        <origin xyz="${caster_wheel_offset_x2} ${caster_wheel_offset_y} ${caster_wheel_offset_z}"/>
    </joint>

    <joint name="caster_wheel_joint3" type="fixed">
        <parent link="chassis"/>
        <child link="caster_wheel3"/>
        <origin xyz="${caster_wheel_offset_x1} ${-caster_wheel_offset_y} ${caster_wheel_offset_z}"/>
    </joint>

    <joint name="caster_wheel_joint4" type="fixed">
        <parent link="chassis"/>
        <child link="caster_wheel4"/>
        <origin xyz="${caster_wheel_offset_x2} ${-caster_wheel_offset_y} ${caster_wheel_offset_z}"/>
    </joint>

    <xacro:macro name="caster" params="pre">
        <link name="caster_wheel${pre}">
            <visual>
                <geometry>
                    <sphere radius="${caster_wheel_radius}"/>
                </geometry>
                <material name="white"/>
            </visual>
            <collision>
                <geometry>
                    <sphere radius="${caster_wheel_radius}"/>
                </geometry>
            </collision>
            <xacro:inertial_sphere mass="${caster_wheel_mass}" radius="${caster_wheel_radius}">
                <origin xyz="0 0 0" rpy="0 0 0"/>
            </xacro:inertial_sphere>
        </link>
    </xacro:macro>

    <xacro:caster pre="1" />
    <xacro:caster pre="2" />
    <xacro:caster pre="3" />
    <xacro:caster pre="4" />

    <gazebo reference="caster_wheel1">
        <material>Gazebo/Black</material>
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>

    <gazebo reference="caster_wheel2">
        <material>Gazebo/Black</material>
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>

    <gazebo reference="caster_wheel3">
        <material>Gazebo/Black</material>
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>

    <gazebo reference="caster_wheel4">
        <material>Gazebo/Black</material>
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>

</robot>